### ISSUE TITLE
ecef2llh

### ISSUE THREAD

**Issue by n-mam** [fbalaban/bluebox_path_planning#1]
Hi,

Just wanted to confirm on if the input coordinates to this function are in kilometers ? I am seeing that the latitude result of this function is considerably off from when I feed the same input ECEF coordinates to https://www.oc.nps.edu/oc2902w/coord/llhxyz.htm?source=post_page---------------------------

Antenna position x (ECEF) : 4156426.04290
Antenna position y (ECEF) : 621742.71480
Antenna position z (ECEF) : 4782158.51560

ecef function results

Longitude : 8.50756
Latitude : 48.6903

www.oc.nps.edu results:

Latitude,Longitude, Height (ellipsoidal) from ECEF

Latitude  : 48.88099   deg N
Longitude : 8.50756   deg E

**Comment by fbalaban** [comment]
Hi,
sorry for the late reply.
They are indeed in km but the function is not accurate, it has been adapted for a project.
I am sorry for the misinformation, I will either correct the code or remove it from github completely.

Please for the calculation refer to the script of oc.nps.edu

**Comment by n-mam** [comment]
Sure Thanks. Only the latitude is off.. this, I guess, essentially varies with different implementations since longitude computation is exact and deterministic. For now, I have picked libswiftnav's transformer which seems to be giving back expected lat. Thanks again.,

https://github.com/swift-nav/libswiftnav/blob/master/src/coord_system.c
